import { Metadata } from "next";
import Header from "./components/Header";
import "./styles/globals.css";

type MyAppProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function MyApp({ children }: MyAppProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}

export default MyApp;
